//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

let R = _R(bundle: Bundle.module)

struct _R {
    let bundle: Foundation.Bundle
    var color: color { .init(bundle: bundle) }

    func color(bundle: Foundation.Bundle) -> color {
        .init(bundle: bundle)
    }

    func validate() throws {}

    /// This `_R.color` struct is generated, and contains static references to 2 colors.
    struct color {
        let bundle: Foundation.Bundle

        /// Color `black`.
        var black: RswiftResources.ColorResource { .init(name: "black", path: [], bundle: bundle) }

        /// Color `white`.
        var white: RswiftResources.ColorResource { .init(name: "white", path: [], bundle: bundle) }
    }
}
