//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

let R = _R(bundle: Bundle.module)

struct _R {
    let bundle: Foundation.Bundle
    var color: color { .init(bundle: bundle) }
    var image: image { .init(bundle: bundle) }

    func color(bundle: Foundation.Bundle) -> color {
        .init(bundle: bundle)
    }

    func image(bundle: Foundation.Bundle) -> image {
        .init(bundle: bundle)
    }

    func validate() throws {}

    /// This `_R.color` struct is generated, and contains static references to 15 colors.
    struct color {
        let bundle: Foundation.Bundle

        /// Color `black`.
        var black: RswiftResources.ColorResource { .init(name: "black", path: [], bundle: bundle) }

        /// Color `darkGrey`.
        var darkGrey: RswiftResources.ColorResource { .init(name: "darkGrey", path: [], bundle: bundle) }

        /// Color `darkTurquoise`.
        var darkTurquoise: RswiftResources.ColorResource { .init(name: "darkTurquoise", path: [], bundle: bundle) }

        /// Color `grey`.
        var grey: RswiftResources.ColorResource { .init(name: "grey", path: [], bundle: bundle) }

        /// Color `lightTurquoise`.
        var lightTurquoise: RswiftResources.ColorResource { .init(name: "lightTurquoise", path: [], bundle: bundle) }

        /// Color `navy`.
        var navy: RswiftResources.ColorResource { .init(name: "navy", path: [], bundle: bundle) }

        /// Color `navy05`.
        var navy05: RswiftResources.ColorResource { .init(name: "navy05", path: [], bundle: bundle) }

        /// Color `navy10`.
        var navy10: RswiftResources.ColorResource { .init(name: "navy10", path: [], bundle: bundle) }

        /// Color `navy20`.
        var navy20: RswiftResources.ColorResource { .init(name: "navy20", path: [], bundle: bundle) }

        /// Color `navy40`.
        var navy40: RswiftResources.ColorResource { .init(name: "navy40", path: [], bundle: bundle) }

        /// Color `navy70`.
        var navy70: RswiftResources.ColorResource { .init(name: "navy70", path: [], bundle: bundle) }

        /// Color `red`.
        var red: RswiftResources.ColorResource { .init(name: "red", path: [], bundle: bundle) }

        /// Color `turquoise`.
        var turquoise: RswiftResources.ColorResource { .init(name: "turquoise", path: [], bundle: bundle) }

        /// Color `white`.
        var white: RswiftResources.ColorResource { .init(name: "white", path: [], bundle: bundle) }

        /// Color `wine`.
        var wine: RswiftResources.ColorResource { .init(name: "wine", path: [], bundle: bundle) }
    }

    /// This `_R.image` struct is generated, and contains static references to 3 images.
    struct image {
        let bundle: Foundation.Bundle

        /// Image `dev_setting`.
        var dev_setting: RswiftResources.ImageResource { .init(name: "dev_setting", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `info`.
        var info: RswiftResources.ImageResource { .init(name: "info", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `setting`.
        var setting: RswiftResources.ImageResource { .init(name: "setting", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    }
}
