//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

let R = _R(bundle: Bundle.module)

struct _R {
    let bundle: Foundation.Bundle
    var color: color { .init(bundle: bundle) }

    func color(bundle: Foundation.Bundle) -> color {
        .init(bundle: bundle)
    }

    func validate() throws {}

    /// This `_R.color` struct is generated, and contains static references to 6 colors.
    struct color {
        let bundle: Foundation.Bundle

        /// Color `grey`.
        var grey: RswiftResources.ColorResource { .init(name: "grey", path: [], bundle: bundle) }

        /// Color `navy`.
        var navy: RswiftResources.ColorResource { .init(name: "navy", path: [], bundle: bundle) }

        /// Color `navy20`.
        var navy20: RswiftResources.ColorResource { .init(name: "navy20", path: [], bundle: bundle) }

        /// Color `navy40`.
        var navy40: RswiftResources.ColorResource { .init(name: "navy40", path: [], bundle: bundle) }

        /// Color `navy70`.
        var navy70: RswiftResources.ColorResource { .init(name: "navy70", path: [], bundle: bundle) }

        /// Color `white`.
        var white: RswiftResources.ColorResource { .init(name: "white", path: [], bundle: bundle) }
    }
}
