name: Setup Ios

runs:
  using: "composite"
  steps:
    - name: set build system
      run: defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1
      shell: bash
    
    - name: cache spm
      uses: actions/cache@v3
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Mutaro.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        
    - name: install dependencies
      run: |
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bash_profile
        eval "$(/opt/homebrew/bin/brew shellenv)"
        brew install licenseplist
      shell: bash          
