name: Setup Ios

runs:
  using: "composite"
  steps:
    - name: set build system
      run: defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1
      shell: bash
    
    - name: cache spm
      uses: actions/cache@v3
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Mutaro.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        
    - name: install dependencies
      run: |
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bash_profile
        eval "$(/opt/homebrew/bin/brew shellenv)"
        brew install licenseplist
      shell: bash
      
    - name: export variable
      with:
        GITHUB_TOKEN: ${{ env.GH_TOKEN }}
        G_DEV_API_KEY: ${{ env.G_DEV_API_KEY }}
        G_DEV_CLIENT_ID: ${{ env.G_DEV_CLIENT_ID }}
        G_DEV_GCM_SENDER_ID: ${{ env.G_DEV_GCM_SENDER_ID }}
        G_DEV_GOOGLE_APP_ID: ${{ env.G_DEV_GOOGLE_APP_ID }}
        G_DEV_REVERSED_CLIENT_ID: ${{ env.G_DEV_REVERSED_CLIENT_ID }}
      run: |
        ./scripts/apply-environment-variable.sh ${G_DEV_CLIENT_ID} ${G_DEV_API_KEY} ${G_DEV_REVERSED_CLIENT_ID} ${G_DEV_GCM_SENDER_ID} ${G_DEV_GOOGLE_APP_ID} ${GITHUB_TOKEN}
      shell: bash
