name: Setup Ios

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      G_DEV_API_KEY:
        required: true
      G_DEV_CLIENT_ID:
        required: true
      G_DEV_GCM_SENDER_ID:
        required: true
      G_DEV_GOOGLE_APP_ID:
        required: true
      G_DEV_REVERSED_CLIENT_ID:
        required: true

runs:
  runs-on: self-hosted
  using: "composite"
  steps:
    - name: set build system
      run: defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1
      shell: bash
    
    - name: cache spm
      uses: actions/cache@v3
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Mutaro.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        
    - name: install dependencies
      run: |
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bash_profile
        eval "$(/opt/homebrew/bin/brew shellenv)"
        brew install licenseplist
      shell: bash          
