//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

let R = _R(bundle: Bundle.module)

struct _R {
    let bundle: Foundation.Bundle
    var color: color { .init(bundle: bundle) }
    var image: image { .init(bundle: bundle) }

    func color(bundle: Foundation.Bundle) -> color {
        .init(bundle: bundle)
    }

    func image(bundle: Foundation.Bundle) -> image {
        .init(bundle: bundle)
    }

    func validate() throws {}

    /// This `_R.color` struct is generated, and contains static references to 1 colors.
    struct color {
        let bundle: Foundation.Bundle

        /// Color `navy`.
        var navy: RswiftResources.ColorResource { .init(name: "navy", path: [], bundle: bundle) }
    }

    /// This `_R.image` struct is generated, and contains static references to 3 images.
    struct image {
        let bundle: Foundation.Bundle

        /// Image `dev_setting`.
        var dev_setting: RswiftResources.ImageResource { .init(name: "dev_setting", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `info`.
        var info: RswiftResources.ImageResource { .init(name: "info", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `setting`.
        var setting: RswiftResources.ImageResource { .init(name: "setting", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    }
}
