name: Build For Debug

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app

jobs:
  distribute:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/Common/setup-ios
      - name: "build debug"
        run: |
          make build-debug-development
