name: Build For Debug

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode-14.1.app

jobs:
  distribute:
    runs-on: self-hosted
    secrets:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      G_DEV_API_KEY: ${{ secrets.G_DEV_API_KEY }}
      G_DEV_CLIENT_ID: ${{ secrets.G_DEV_CLIENT_ID }}
      G_DEV_GCM_SENDER_ID: ${{ secrets.G_DEV_GCM_SENDER_ID }}
      G_DEV_GOOGLE_APP_ID: ${{ secrets.G_DEV_GOOGLE_APP_ID }}
      G_DEV_REVERSED_CLIENT_ID: ${{ secrets.G_DEV_REVERSED_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/Common/setup-ios
      - name: "build debug"
        run: |
          make build-debug-development
        
