name: Check Swift Dependency

on:
  workflow_dispatch
#   schedule:
#     - cron: "50 7 * * 1-5"
#     - cron: "40 7 * * 1-5"
#     - cron: "30 7 * * 1-5"
#     - cron: "20 7 * * 1-5"
#     - cron: "10 7 * * 1-5"

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run Ruby script
        id: ruby-script
        env:
          FILE_PATH: "../Mutaro/Mutaro.xcworkspace/xcshareddata/swiftpm/Package.resolved"
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          result=$(ruby ./.github/workflows/swift_dependency_check_latest_version.rb ${FILE_PATH} ${GH_TOKEN})
          if [ -z "$result" ] || [ "$result" = '[{}]' ]; then
            exit 0
          fi
          echo "result=${result}" >> $GITHUB_OUTPUT

      - name: Setup and Remove related branch and pr
        id: setup-remove-branch-pr
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git fetch --prune --all
#           git branch -r --format='%(refname:lstrip=3)' | grep '^spm/update-dependency/' > branches.txt
          
#           while read -r branch; do
#             git push origin --delete "$branch"
#             branch_name=${branch#*/}
#             hub api "/repos/:owner/:repo/pulls?state=open" | jq -r ".[] | select(.head.ref == \"$branch_name\") | .number" | xargs -I {} hub api -X DELETE "/repos/:owner/:repo/pulls/{}"
#           done < branches.txt

#       - name: Create Branch and PR
#         id: create-branch-pr
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           current_datetime=$(date +"%Y-%m-%d-%H-%M")
          
#           branchName="spm/update-dependency/${current_datetime}"
          
#           git branch $branchName
#           git switch $branchName
#           git commit --allow-empty -m "Empty-Commit"
#           git push --set-upstream origin $branchName
          
#           pr_number=$(gh pr create --base develop --title "Update Swift Package Dependency" --body "" | sed -n 's#.*https://github.com/[^/]\+/[^/]\+/pull/\([0-9]\+\).*#\1#p')
#           echo "pull-request-number=${pr_number}" >> $GITHUB_OUTPUT
          
#       - name: Add comments to PR
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           PULL_REQUEST_NUMBER: ${{ steps.create-branch-pr.outputs.pull-request-number }}
#         run: |
#           result='${{ steps.ruby-script.outputs.result }}'
#           for item in $(echo "$result" | jq -c '.[]'); do
#             currentVersion=$(echo "$item" | jq -r '.currentVersion')
#             newVersion=$(echo "$item" | jq -r '.newVersion')
#             repository=$(echo "$item" | jq -r '.repository')
            
#             comment="CurrentVersion: $currentVersion<br>NewVersion: $newVersion<br>Repository: $repository"
#             gh issue comment "${PULL_REQUEST_NUMBER}" -b "$comment"
#           done
